### ISSUE TITLE
Cannot import main theme icons

### ISSUE THREAD

**Issue by laventnc** [handsontable/handsontable#11690]
We are trying to modify the theme as described in [the documentation](https://handsontable.com/docs/javascript-data-grid/handsontable-design-system/).

However, the output from the theme generator generates a scss file with: `@use "utils/main/icons"`. Which does not resolve when loading the generated scss file.

I'm loading my custom theme after the base CSS file (as described [here](https://handsontable.com/docs/javascript-data-grid/themes/#create-a-custom-theme)).

```vue
<style src="handsontable/styles/handsontable.min.css" />
<!-- <style src="handsontable/styles/ht-theme-main.min.css" /> -->
<style src="~/assets/styles/handsontable/theme-custom.scss" />
```

It seems like my only solution is to copy the two _icon files (from main/utils and utils), but this is obviously not a sustainable plan.

**Comment by adrianszymanski89** [comment]
Hi @laventnc 

Thank you for contacting us. Did you try compiling the SCSS file first and then importing it as a regular CSS file?

**Comment by laventnc** [comment]
Yeah I figured that was the case. I'm using vite and admittedly this area is a bit of a gap in my knowledge.

I believe vite takes care of this, I think i just need the correct import path to the icons utils. It's definitely not `utils/main/icons`

**Comment by adrianszymanski89** [comment]
Hi @laventnc 

I would still recommend compiling the SCSS file to CSS and see if that resolves the problem. If not, can you please share your custom theme implementation in StackBlitz so I can check it?

**Comment by laventnc** [comment]
I'm a bit confused @adrianszymanski89 , I'm using a [custom theme](https://handsontable.com/docs/javascript-data-grid/handsontable-design-system/#use-tokens-to-generate-a-theme) generated with the figma design tokens passed into your [theme generator](https://github.com/handsontable/handsontable-figma).

My expectation was that I would be able to simply place this in my project.
```scss
// custom-theme.scss
@use "sass:color";
@use "utils/main/icons";

@mixin light {
  --ht-font-size: 14px;
  // ...
}

@mixin dark {
}

.ht-theme-main,
.ht-theme-main-dark,
.ht-theme-main-dark-auto {
  @include light();
}

/* Dark mode */
.ht-theme-main-dark {
  @include dark();
}

/* Auto dark mode */
@media (prefers-color-scheme: dark) {
  .ht-theme-main-dark-auto {
    @include dark();
  }
}

/* Icons */
[class*=ht-theme-main] {
  @include icons.output();
}
```

The issue occurs when compiling the file to css as the line `@use "utils/main/icons"` doesn't resolve. It seems like I basically need to copy the icon file from the source code, as the source code doesn't appear to export the [referenced mixin](https://github.com/handsontable/handsontable/blob/develop/handsontable/src/styles/themes/utils/main/_icons.scss).

At the very least, the documentation doesn't make it clear how to modify the import path to import from the uncompiled source linked above
