### ISSUE TITLE
Padding on td, th breaks with fixed column cell sizes with 0.11.1

### ISSUE THREAD

**Issue by wolever** [handsontable/handsontable#1753]
To recreate, add a CSS rule:

```css
.handsontable th,
.handsontable td {
    padding: 5px;
}
```

The fixed column will be 10px larger than the non-fixed column: 
![cell size bug example](https://cloud.githubusercontent.com/assets/59575/4194181/76a97bec-37aa-11e4-8a10-88faafa02f79.jpg)

I haven't dug into things too much, but it seems like it has something to do with the fact that the fixed column's height is explicitly calculated + set: `<th class="curRow" style="height: 32px;">…</th>`
