### ISSUE TITLE
Enhancement suggestion: being able to rotate the header

### ISSUE THREAD

**Issue by pfvilquin** [handsontable/handsontable#2021]
Would be convenient when creating a table with long headers if we could define an angle for the column headers, for instance rotate them at 45degres.

**Comment by t00f** [comment]
+1

If you are willing to have fixed size colums, there should be an easy way from [codepen](http://codepen.io/chriscoyier/pen/Fapif)

I am using AngularJS wrapper ngHandsontable but it might be a good start for you as well. Simply add class `table-header-rotated` and here is the adjusted CSS:

``` css
.table-header-rotated th {
  padding: 5px 10px;
}
.table-header-rotated td {
  text-align: center;
  padding: 2px;
}

.table-header-rotated .handsontable th {
    vertical-align: middle;
    overflow: visible;
    background: #fff;
    border: 0 !important;
}

.table-header-rotated th {
  height: 150px;
  white-space: nowrap;

}
.table-header-rotated th > div {
  -webkit-transform: translate(25px, 51px) rotate(315deg);
      -ms-transform: translate(25px, 51px) rotate(315deg);
          transform: translate(25px, 51px) rotate(315deg);
  width: 30px;
}
.table-header-rotated th > div > span {
  border-bottom: 1px solid #ccc;
  padding: 5px 10px;
}
.table-header-rotated th.row-header {
  padding: 0 10px;
}
```
