### ISSUE TITLE
Bootstrap checkbox disrupting row heights with overflow: auto

### ISSUE THREAD

**Issue by slat** [handsontable/handsontable#2338]
Based on the bootstrap integration & scroll demo.
http://jsfiddle.net/24524q9y/
Easily remedied with:
```css
.htCheckboxRendererInput {
    float: left;
}
```
