### ISSUE TITLE
Autocomplete Display Issues

### ISSUE THREAD

**Issue by YipYipX4** [handsontable/handsontable#2380]
I am using Chrome version 41.0.2272.118 m
In my app, I'm using handsontable version 13.1, but I've duplicated my issue in jsfiddle using version 14.1 and I was also able to duplicate my fixes with some minor tweaks.

Try this jsfiddle:
http://jsfiddle.net/wz60bf0a/2/

Try the last autocomplete in the "Car" column of the first table and notice these issues:
- If the table column is narrow, so is the autocomplete.  Most items end with ellipses.  I have fixed this with a min-width of 200px for the outer drop-down and a min-width of 180px for the content (to avoid a horizontal scroll bar due to the vertical scroll bar). It would be nicer to make the drop-down auto-fit the content (up to some reasonable max-width), but I don't know how to do that.  (Of course, my real life app typically has options a bit wider than this example, so that is why I use a min-width of 180px.  Anything wider will cause a horizontal scroll bar to appear, which is undesirable.)
- The drop-down list shows _under_ the headers of the next table!  I fixed this with a z-index tweak.
- If you scroll to the bottom of the list, you can "see through" the list to the content below (see screen shot). I fixed this with a background-color and also removed the border for the content inside the vertical scroll bar.
- Also, it would be nice to have a border and drop-shadow around the entire drop-down list (not just the list inside the scrollbar).  I added this with a border and box-shadow on the autocompleteEditor.

To see my fixes, uncomment the CSS in the jsfiddle and notice the improvement!  Note: In both cases, I can't seem to interact with the drop-down with the mouse, but it works with the keyboard.  Is that a jsfiddle issue?  Or a new issue in version 14.1?  That problem doesn't occur in my app where I use version 13.1 currently (and I do have multiple instances of handsontable in a single page).

_Before:_
![image](https://cloud.githubusercontent.com/assets/2667349/7192045/06670c60-e447-11e4-94fe-2b91215be143.png)

_After:_
![image](https://cloud.githubusercontent.com/assets/2667349/7192051/12af253e-e447-11e4-930a-cb55039d27cf.png)

**Comment by AMBudnik** [comment]
I also reproduced it. Thanks for sharing!

**Comment by YipYipX4** [comment]
FYI, my jsfiddle references the following, which has been updated to 0.15.0-beta2 as of right now:
http://handsontable.com/dist/handsontable.full.js

Consequently, my css fixes do not completely work anymore.  View screenshots above to see how it should look (or update the jsfiddle to reference version 14.1 and uncomment my css fixes).

Nonetheless, the jsfiddle still reproduces all of the issues, which remain just as bad in version 0.15.0-beta2.

**Comment by YipYipX4** [comment]
Here's an updated "before" (with CSS fixes commented out):
http://jsfiddle.net/wz60bf0a/3/

And here's the "after" with **updated CSS fixes for 0.15.0-beta3**:
http://jsfiddle.net/wz60bf0a/4/

Note: On the first click, about half the items in the autocomplete do not render when you scroll down to the bottom, but they all render if you close the autocomplete and reopen it.  This occurs even without my CSS fixes, so I'll file a separate issue for that.

Here's the CSS that I added:
```css
.handsontableInputHolder
{
  z-index: 1000;
}

.handsontable.autocompleteEditor
{
  border: 1px solid #AAAAAA;
  box-shadow: 10px 10px 15px #AAAAAA;
  background-color: white;
  min-width: 200px;
}

.handsontable.autocompleteEditor.handsontable
{
  padding-right: 0px;
}

.handsontable.listbox .ht_master table
{
  border: none;
}

.autocompleteEditor .wtHolder 
{
  min-width: 200px;
}


.autocompleteEditor .htCore
{
  border: none !important;
  -webkit-box-shadow: none !important;
  box-shadow: none !important;
  min-width: 180px !important;
}
```

**Comment by YipYipX4** [comment]
Here's a jsFiddle showing that the poor behavior still occurs in handsontable version 15.0:
http://jsfiddle.net/wz60bf0a/7/

And here's the same jsFiddle with my fixes applied:
http://jsfiddle.net/wz60bf0a/8/

Here are the latest CSS fixes:
```css
.handsontableInputHolder
{
  z-index: 1000;
}

.handsontable.autocompleteEditor
{
  border: 1px solid #AAAAAA;
  box-shadow: 10px 10px 15px #AAAAAA;
  background-color: white;
  min-width: 200px;
}

.handsontable.autocompleteEditor.handsontable
{
  padding-right: 0px;
}

.handsontable.listbox .ht_master table
{
  border: none;
}

.autocompleteEditor .wtHolder 
{
  min-width: 200px;
}


.autocompleteEditor .htCore
{
  border: none !important;
  -webkit-box-shadow: none !important;
  box-shadow: none !important;
  min-width: 180px !important;
}

.autocompleteEditor .ht_clone_top, .autocompleteEditor .ht_clone_left
{
  display: none;
}

```
