### ISSUE TITLE
Problem with row header showing on top of the sidebar(overlapping)  from bootstrap file

### ISSUE THREAD

**Issue by yash-jain** [handsontable/handsontable#3131]
the rowHeader and colHeader when used are overlapping when used with the bootstrap file sidebar function.Other table elements works fine but this creates a problem.Any solutions?

**Comment by AMBudnik** [comment]
Hi @yash-jain can you create an example using Handsontable with bootstrap sidebar to illustrate the issue?

**Comment by yash-jain** [comment]
I am using a custom bootstrap theme actually ..i can share the css content of the sidebar class if needed and here is the screenshot.
Here i am using rowHeader and colHeader.As you can see in the 2nd screenshot ...the rowHeader and colHeader overlapps with the sidebar and also with the header when page is scrolled.It comes at the front 


<img width="240" alt="sss1e" src="https://cloud.githubusercontent.com/assets/11359447/12393167/0e16f7e2-be1a-11e5-8eb4-88d02512d2ea.PNG">
<img width="200" alt="ss2" src="https://cloud.githubusercontent.com/assets/11359447/12393168/0e21d8ba-be1a-11e5-8249-abe6a322d95f.PNG">

**Comment by AMBudnik** [comment]
Hi @yash-jain thanks for sharing. Do you have any additional styles for Handsontable?

**Comment by yash-jain** [comment]
no Sir i do not have any additional styles for that .Just i have used the handsontable full.js and .css file for it

**Comment by budnix** [comment]
@yash-jain I see 2 solutions for this issue. You can add `z-index` to your side menu for instance `z-index: 120` or you can overwrite Handsontable overlays z indexes (decrease their default values).

```css
.ht_clone_top {
  z-index: 11 !important;
}

.ht_clone_left {
  z-index: 12 !important;
}

.ht_clone_top_left_corner,
.ht_clone_bottom_left_corner {
  z-index: 13 !important;
}
```
