### ISSUE TITLE
Allow 'overflow: auto' for parent element

### ISSUE THREAD

**Issue by Sune1337** [handsontable/handsontable#3432]
If a handsontable has a parent at any level that has the 'overflow: auto' css style set, the height of the table becomes zero; rendering the table invisible.

Example: https://jsfiddle.net/4ecg5L1o/3/

**Comment by xfight0** [comment]
I have encountered this problem, it is very strange.

**Comment by Yimiprod** [comment]
Same problem, and if i don't set overflow: auto, the height and width are based on body size for me.

**Comment by jansiegel** [comment]
Hi, @Sune1337!

What effect are you trying to achieve? If you're aiming for a fixed-size implementation, you should probably use `overflow: hidden` on the table container. 

I think this post on our blog might be helpful, when it comes to defining the size of Handsontable: https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable

**Comment by Sune1337** [comment]
I would like to have Handsontable to display as many columns and rows as i feed it without scrolling.
That's how Handsontable works out of the box; only if there happens to be a div with overflow set somewhere up the DOM, Handsontable seems to adjust it's height to match that element.

The reason to use overflow in CSS can according to me be a multitude of reasons. In my case, controlling the height of Handsontable is not one of them.
I ran into the problem where i modified an existing layout that used overflow to strech content to fill the horizontal space after a floating element: https://jsfiddle.net/4ecg5L1o/6/

(this fiddle also displays the problem described in #3433)

Do note that this does not need to be an immediate parent, it could very well be 10 parents up in the DOM tree.

**Comment by GabiAxel** [comment]
I'm trying to achieve the same effect - just have the entire Handsontable, with all the rows, render and consume as much height as it needs without having scrollbars in it. I do have scrollbars on the container where scroll:auto style is defined, and with the current behaviour I get a scrollable space (Handsontable) inside another scrollable container, which is obviously bad experience.

I worked around it by setting the Handsontable option `renderAllRows` to true, and adding the following CSS rules to override those of Handsontable:

````css
.wtHolder {
  width: auto !important;
  height: auto !important;
}

.wtHider {
  padding: 0 5px 5px 0;
}

.ht_clone_top {
  width: auto !important;
}

.ht_clone_left {
  height: auto !important;
}

.ht_clone_top, .ht_clone_left, .ht_clone_top_left_corner {
  z-index: 1 !important;
}
````

**Comment by Yimiprod** [comment]
My case is simple, since the table can overflow the container, i need to let it scroll on the x axis but let him flow on the y axix.

```css
.handsontable-container {
  overflow-x: auto;
}
```

This make the height at 0, and make other display error when selecting cells from the bottom and right lines.
