### ISSUE TITLE
Cursor as text

### ISSUE THREAD

**Issue by Aymkdn** [handsontable/handsontable#57]
Hi,

Great stuff here. Congrats !

Maybe you may want to change your CSS file to add this :

``` css
.dataTable td { cursor:text }
```

That way a text cursor will appear when the mouse is over a cell. A good way for the user to know he can enter something into the cell.
