### ISSUE TITLE
Allow to remove the action arrow from cells with an autocomplete renderer

### ISSUE THREAD

**Issue by AMBudnik** [handsontable/handsontable#6003]
### Description

Allow removing the action arrow from cells with an autocomplete renderer, which are: autocomplete, dropdown, handsontable and date.

### Your environment
* Handsontable version: 7.0.1
* Browser Name and version: n/a
* Operating System: n/a

**Comment by wojciechczerniak** [comment]
@AMBudnik What's wrong with CSS?

```css
.handsontable .htAutocompleteArrow {
  display: none;
}
```

**Comment by AMBudnik** [comment]
Thanks for mentioning. Also, I liked the idea with

```css
.handsontable .htReadOnly .htAutocompleteArrow {
  display: none;
}
```

so it should cover all the scenarios that I have on my mind. Thanks!
