### ISSUE TITLE
Set width:100% for the table

### ISSUE THREAD

**Issue by alvarotrigo** [handsontable/handsontable#718]
I was able to set the table width to 100% in version  `0.8.23` by just adding this style:

``` css
#container.handsontable table{
    width:100%;
}
```

Now, I have upgraded to 0.9.2 and I've noticed it doesn't work anymore.
Here's the fiddle:
http://jsfiddle.net/imac/8hv4z/9/

It is hidden many columns instead.
Is it possible to set the table width to 100% in order to fill all the page? Thanks.
