### ISSUE TITLE
Docs: Cookiebot message content not visible in the dark theme

### ISSUE THREAD

**Issue by warpech** [handsontable/handsontable#8987]
### Description

Cookiebot button "Allow necessary cookies only" is not visible in the dark theme of the docs.

Steps to reproduce:

1. Go to private mode of your web browser
2. Open the docs page e.g. https://handsontable.com/docs/#get-started-with-sample-apps
3. Switch to the dark theme
4. See the color of the text in the Cookiebot's message box

![image](https://user-images.githubusercontent.com/566463/143952393-fb462d41-d8ec-4f4b-94ec-38e0dd653555.png)

I think that the following CSS might fix it:

```css
html.theme-dark #CybotCookiebotDialogFooter .CybotCookiebotDialogBodyButton {
  color: #f5f6f7;
}
```

But there is more to it - after clicking "Show details", more texts are not visible:

![image](https://user-images.githubusercontent.com/566463/143952344-e943700d-0c29-4117-8d43-3f1cdbadeb84.png)
