### ISSUE TITLE
[RTL] Add validation logic into the sass-rtl-loader

### ISSUE THREAD

**Issue by Siemienik** [handsontable/handsontable#9113]
### Description

#9102 introduces support for `inset-inline-start` and `inset-inline-end` properties.
However now it is available some incorrect scenarios:

* `text-align: inset-inline-start`, should be `text-align: inline-start`.
* `border-inset-inline-end-width`, should be `border-inline-end-width`.
* `inline-end: 5px;`, should be `inset-inline-end: 5px;`.
actually, the positioning purposes are the only one scenarious when `inset` prefix occurs.

This issue assumes adding a validation that protects us against incorrect usages. (Currently, only sonar cloud catches them).

There is one of two possible behaviour for catcher incorrect behaviours: (needs decision which we prefer)
1. Throw a warning about incorrect usages.
2. Ignore and don't transform to IE compatible `left`/`'right`

**Comment by budnix** [comment]
Thanks for creating the issue. I would like to share my observations. Playing with the changes that #9102 fixes I see the following bottlenecks:
 * There is still possible to declare a CSS property as `inline-end`. It's not CSS spec-compliant and if used in an incomprehensible manner can lead to visual bugs.
```scss
.foo {
  inline-end: 10px;
}
```
Would generate
```scss
.foo {
  right: 10px;
}
[dir=rtl] .foo {
  left: 10px;
}
```
  * I would opt-in for using allow list (or pattern list) in the sass loader to make sure that typo mistakes would not be processed. Otherwise, it could be more challenging - especially for new developers, to find a typo based on the output file.
```scss
.foo {
  marginm-inline-end: 10px;
}
```
Would generate
```scss
.foo {
  /* original typo is processed so it's hard to find the relationship between original line */
  marginm-right: 10px;  
}
[dir=rtl] .foo {
  marginm-left: 10px;
}
```
  * The CSS comments are unnecessarily processed.
```scss
/* Start of the inline-end story */
.foo {
  border: none;
}
/* End of the inline-end story */
```
Generates
```scss
/* Start of the right story */
.foo {
  border: none;
}

[dir=rtl] {
  /* Start of the left story */
}
[dir=rtl] .foo {
  border: none;
}

/* End of the inline-end story */
```
